name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '^3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: make install
      
  test:
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Run tests
      run: make test

    - name: Run test coverage
      run: make testcov
      
    - name: Format code
      run: make format
      
    - name: Clean up
      run: make clean
      
